[package]
name = "clippi"
version = "0.1.0"
description = "clipping app"
default-run = "clippi"
authors = ["irusei"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
# The `_lib` suffix may seem redundant but it is necessary
# to make the lib name unique and wouldn't conflict with the bin name.
# This seems to be only an issue on Windows, see https://github.com/rust-lang/cargo/issues/8519
name = "clippi_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
windows = { version = "0.58", features = [
    "Win32_Foundation",
    "Win32_UI_WindowsAndMessaging",
    "Win32_System_Threading",
] }
tauri = { version = "2", features = ["protocol-asset", "tray-icon", "image-png"] }
tauri-plugin-opener = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
anyhow = "1"
env_logger = "0.11"
indicatif = "0.18"

libobs-simple = { git = "https://github.com/irusei/clippi-libobs-rs.git", package = "libobs-simple", features = ["window-list"] }
libobs-wrapper = { git = "https://github.com/irusei/clippi-libobs-rs.git", package = "libobs-wrapper" }
libobs-window-helper = { git = "https://github.com/irusei/clippi-libobs-rs.git", package = "libobs-window-helper" }

tokio = { version = "1", features = ["full"] }
wmi = "0.18.4"
dirs = "6.0.0"
regex = "1.12.3"
device_query = "4.0.1"
uuid = {
    version = "1.23.1",
    features = ["v4"]
}
discord-rpc-client = "0.4.0"

